import datetime
t = datetime.time(5,25,1)
print(t)
print(t.minute)
print(datetime.time.min)
print(datetime.time.max)
print(datetime.time.resolution)
d1 = datetime.date(2015,3,11)
print(d1)
d2 = d1.replace(year=1995)
print(d2)
